substitutions:
  friendly_name: Synology DS925+ Fan

esphome:
  name: nas-fan

# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min

#########################
# ESP32 AND NETWORK SETUP

esp32:
  variant: esp32
  framework:
    type: arduino

# pid climate log update is noisy, dial it back to warn
logger:
  level: DEBUG
  logs: 
    climate: ERROR
    dht: WARN

# Automatically blinks during boot (device not yet ready)
status_led:
  pin:
    number: 12

# default HA integration, OTA updater and backup http web portal
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
  
wifi:
  # Read the wifi/pass from secrets.yaml:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

number:
  ## OPTIONAL:
  # RECEIVE KP, KI and KD parameters from input_text.kx helpers in 
  # Home Assistant. See the PID controller below
  # These helper values will get saved to flash thus permanently over-riding 
  # the initial values set in the PID below.

  # KP
  - platform: template
    name: kp
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.3
    min_value: 0
    max_value: 50
    step: 0.001
    optimistic: true
    set_action: 
      lambda: |- 
        id(nas_thermostat).set_kp( x );

  # KI
  - platform: template
    name: ki
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.0015
    min_value: 0
    max_value: 50
    step: 0.0001
    optimistic: true
    set_action: 
      lambda: id(nas_thermostat).set_ki( x );

  # KD
  - platform: template
    name: kd
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.0
    min_value: -50
    max_value: 50
    step: 0.001
    optimistic: true
    set_action: 
      lambda: id(nas_thermostat).set_kd( x );

  # Set threshold low
  - platform: template
    name: Deadband Threshold Low
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: -1.0
    min_value: -20
    max_value: 0
    step: 0.1
    optimistic: true
    set_action: 
      lambda: id(nas_thermostat).set_threshold_low( x );

  # Set threshold high
  - platform: template
    name: Deadband Threshold High
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.4
    min_value: 0
    max_value: 20
    step: 0.1
    optimistic: true
    set_action: 
      lambda: id(nas_thermostat).set_threshold_high( x );

  # Set ki multiplier
  - platform: template
    name: Deadband ki Multiplier
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.04
    min_value: 0
    max_value: .2
    step: 0.01
    optimistic: true
    set_action: 
      lambda: id(nas_thermostat).set_ki_multiplier( x );

  - platform: template
    name: "Overheat Max Fan Speed Percentage"
    id: max_overheat_fan_limit_percentage
    unit_of_measurement: "%"
    min_value: 0.3
    max_value: 0.9
    step: 0.01
    optimistic: true
    restore_value: true
    initial_value: 0.8

  - platform: template
    name: "Cool Temperature Threshold"
    id: cool_temp_threshold
    unit_of_measurement: "°C"
    min_value: 20.0
    max_value: 40.0
    step: 0.1
    optimistic: true
    restore_value: true
    initial_value: 27.5

text_sensor:

  # Send IP Address
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address

  # Send Uptime in raw seconds
  - platform: template
    name: $friendly_name Uptime
    id: uptime_human
    icon: mdi:clock-start

sensor:

  # Send WiFi signal strength & uptime to HA
  - platform: wifi_signal
    name: $friendly_name WiFi Strength
    update_interval: 20s

  # This is a bit of overkill. It sends a human readable 
  # uptime string 1h 41m 32s instead of 6092 seconds
  - platform: uptime
    name: $friendly_name Uptime
    id: uptime_sensor
    update_interval: 20s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            # Custom C++ code to generate the result
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  # Read the Tacho PIN and show measured RPM as a sensor (only with 4-pin PWM fans!)
  # See instructions here: https://esphome.io/components/sensor/pulse_counter.html
  - platform: pulse_counter
    pin: 
      number: GPIO21   # Connect to any input PIN on the ESP
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan_speed_1
    name: $friendly_name Fan Speed 1
    accuracy_decimals: 0
    update_interval: 15s
    filters:
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...

  - platform: pulse_counter
    pin: 
      number: GPIO19   # Connect to any input PIN on the ESP
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan_speed_2
    name: $friendly_name Fan Speed 2
    accuracy_decimals: 0
    update_interval: 15s
    filters:
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...

  - platform: homeassistant
    name: "NAS Thermostat Temperature"
    entity_id: sensor.nas_thermostat_set_temperature
    id: ha_thermo_temp

########################################################
# START THE FAN CONTROLLER SETUP

  - platform: template
    name: $friendly_name p term
    id: p_term
    unit_of_measurement: "%"
    accuracy_decimals: 2

  - platform: template
    name: $friendly_name i term
    id: i_term
    unit_of_measurement: "%"
    accuracy_decimals: 2

  - platform: template
    name: $friendly_name d term
    id: d_term
    unit_of_measurement: "%"
    accuracy_decimals: 2

  - platform: template
    name: $friendly_name output value
    unit_of_measurement: "%"
    id: o_term
    accuracy_decimals: 2

  - platform: template
    name: $friendly_name error value
    id: e_term
    accuracy_decimals: 2

  - platform: template
    name: $friendly_name is in deadband
    id: in_deadband_term
    accuracy_decimals: 0

  # GET ENVIRONMENT TEMP/HUMIDITY FROM DHT22
  - platform: dht
    pin: GPIO13
    temperature:
      name: "Environment Temperature"
      id: nas_fan_env_temperature
      accuracy_decimals: 2

      # If you don't smooth the temperature readings 
      # the PID controller over reacts to small changes.
      filters:
        - offset: -1.1
        - exponential_moving_average:  
            alpha: 0.1
            send_every: 1

    humidity:
      name: "Environment Humidity"
      id: nas_fan_env_humidity

    # the DHT22 can only be read every 0.5s.
    update_interval: 2s

  # GET BACKGROUND TEMP/HUMIDITY FROM DHT22
  - platform: dht
    pin: GPIO15
    temperature:
      name: "Background Temperature"
      id: nas_fan_bg_temperature
      accuracy_decimals: 2

      # If you don't smooth the temperature readings 
      # the PID controller over reacts to small changes.
      filters:
        - offset: 0.2
        - exponential_moving_average:  
            alpha: 0.1
            send_every: 1

    humidity:
      name: "Background Humidity"
      id: nas_fan_bg_humidity

    # the DHT22 can only be read every 0.5s.
    update_interval: 2s

  # Every time the fan speed is updated, this sensor will
  # also be updated for displaying on the frontend. 
  # See proxy_output.
  - platform: template
    name: "Fan Speed (PWM Voltage)"
    unit_of_measurement: "%"
    id: fan_speed_pwm_voltage

binary_sensor:
  - platform: template
    name: "Background Overheat Mode"
    id: bg_overheat_mode
    lambda: |-
      float thermo_temp = id(ha_thermo_temp).state;
      float env_temp = id(nas_fan_env_temperature).state;
      float bg_temp = id(nas_fan_bg_temperature).state;

      return env_temp > thermo_temp && int(bg_temp) > int(env_temp);

output:
  # Wire this pin (23) into the PWM pin of your 12v fan
  # ledc is the name of the pwm output system on an esp32
  - platform: ledc
    id: nas_fan_speed
    pin: GPIO23

    # 25KHz is standard PC fan frequency, minimises buzzing
    frequency: "25000 Hz" 

    # my fans stop working below 13% powerful.
    # also they're  powerful and loud, cap their max speed to 80%
    min_power: 13%
    max_power: 80%

    # At 0, actually turn it off, otherwise the power keeps going.
    zero_means_zero: true

  # This proxy output takes its input
  # if the manual fan control is on, use the level from that
  # otherwise use the PID control value.
  # Then publish the result to the fan (ledc) and 
  # also publish to the template output sensor
  - platform: template
    id: proxy_output
    type: float
    write_action:
      lambda: |-
        float write_val = 
          (id(manual_fan_control).state) ?
            id(manual_fan_control).speed / 100.0 : state*1.0;

        float thermo_temp = id(ha_thermo_temp).state;
        float env_temp = id(nas_fan_env_temperature).state;
        float bg_temp = id(nas_fan_bg_temperature).state;

        // Background overheat mode, use the max_overheat_fan_limit_percentage
        if (env_temp > thermo_temp && int(bg_temp) > int(env_temp)) {
          float bg_limit = id(max_overheat_fan_limit_percentage).state;
          write_val = fmax(0.2, write_val * bg_limit);
        }

        id(nas_fan_speed).set_level(write_val);
        id(fan_speed_pwm_voltage).publish_state(write_val*100.0);
  
  # LEDs for indicating the temperature
  - platform: gpio
    pin: 27
    id: led_temp_low
  - platform: gpio
    pin: 25
    id: led_temp_mid
  - platform: gpio
    pin: 32
    id: led_temp_high

# Logics for controlling the temperature LEDs
interval:
  - interval: 0.5s
    then:
      - lambda: |-
          auto reset_leds = []() {
            id(led_temp_low).turn_off();
            id(led_temp_mid).turn_off();
            id(led_temp_high).turn_off();
          };

          // Turn off all the LEDs, when not reading the data from HA
          if (!id(ha_thermo_temp).has_state()) {
            reset_leds();

            return;
          }

          float env_temp = id(nas_fan_env_temperature).state;
          float cool_temp_thres = id(cool_temp_threshold).state;
          float hot_temp_thres = id(ha_thermo_temp).state;

          // reset all temperature LEDs
          reset_leds();

          if (env_temp < cool_temp_thres) {
            id(led_temp_low).turn_on();
          } else if (env_temp >= cool_temp_thres && env_temp <= hot_temp_thres) {
            id(led_temp_mid).turn_on();
          } else if (env_temp > hot_temp_thres) {
            id(led_temp_high).turn_on();
          }

# If you turn this on, you can manually set the fan speed.
# The PID will be ignored. This is done via the proxy_output.
fan:
  - platform: speed
    id: manual_fan_control
    output: proxy_output
    name: "Manual Fan Speed"

# Expose a PID-controlled Thermostat
# Manual: https://esphome.io/components/climate/pid.html
climate:
  - platform: pid
    name: "NAS Fan Thermostat"
    id: nas_thermostat
    sensor: nas_fan_env_temperature

    # It is summer right now, so 30c is a decent target.
    default_target_temperature: 30°C
    cool_output: proxy_output

    # ON state change, publish the values to the x_term numbers defined 
    # above, so that they can be viewed in HA
    on_state:
      - sensor.template.publish:
          id: p_term
          state: !lambda 'return -id(nas_thermostat).get_proportional_term() * 100.0;'
      - sensor.template.publish:
          id: i_term
          state: !lambda 'return -id(nas_thermostat).get_integral_term()* 100.0;'
      - sensor.template.publish:
          id: d_term
          state: !lambda 'return -id(nas_thermostat).get_derivative_term()* 100.0;'
      - sensor.template.publish:
          id: o_term
          state: !lambda 'return -id(nas_thermostat).get_output_value()* 100.0;'
      - sensor.template.publish:
          id: in_deadband_term
          state: !lambda 'return id(nas_thermostat).in_deadband();'
      - sensor.template.publish:
          id: e_term
          state: !lambda 'return -id(nas_thermostat).get_error_value();'

    # The extents of the HA Thermostat
    visual:
      min_temperature: 20 °C
      max_temperature: 50 °C

    # See the README for setting up these parameters.
    # These are over ridden by the number templates above.
    control_parameters:
      kp: 0.3
      ki: 0.0015
      kd: 0
      max_integral: 0.0
      output_averaging_samples: 1
      derivative_averaging_samples: 5

    # How to behave when close to the target temperature?
    deadband_parameters:
      threshold_high: 0.4°C
      threshold_low: -1.0°C
      kp_multiplier: 0.0
      ki_multiplier: 0.04
      kd_multiplier: 0.0
      deadband_output_averaging_samples: 15

switch:
  # Expose an ESP32 restart button to HA
  - platform: restart
    name: ${friendly_name} ESP32 Restart
    id: nas_fan_restart

# Restart every day at 12:30am. 
# I've had some memory issues lockup 
# the device after a couple weeks
time:
  - platform: homeassistant
    on_time:
      # Every morning at 12:30am
    - seconds: 0
      minutes: 30
      hours: 0
      then:
       - switch.turn_on: nas_fan_restart

# I was able to find good KP,KI,KD values manually, per the instructions,
# but you can try pressing the autotune button from home assistant and copying the 
# values it produces. 
# See more at: https://esphome.io/components/climate/pid.html#climate-pid-autotune-action
button:
- platform: template
  name: "PID Climate Autotune"
  on_press: 
    - climate.pid.autotune: nas_thermostat
